
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.bitapp.paper.page;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-28T20:17:30.687+09:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "pageService",
                      portName = "pageServicePort",
                      targetNamespace = "http://paper.bitapp.de/page",
                      wsdlLocation = "file:/C:/Users/bond/git/PaperTest2/paper2.wsdl",
                      endpointInterface = "de.bitapp.paper.page.PageServicePortType")
                      
public class PageServicePortTypeImpl implements PageServicePortType {

    private static final Logger LOG = Logger.getLogger(PageServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see de.bitapp.paper.page.PageServicePortType#ping(de.bitapp.paper.page.StatusCodeTyp  status ,)java.lang.String  mySimple )*
     */
    public void ping(javax.xml.ws.Holder<StatusCodeTyp> status,java.lang.String mySimple) { 
        LOG.info("Executing operation ping");
        System.out.println(status.value);
        System.out.println(mySimple);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
